
abundance_table: "/mnt/data/holosimulator.csv"
outdir: "results/fastqs"
refdir: "refs"
workdir: "work"

mean_seq_depth_pairs: 2000000
mean_seq_depth_variance: 2500000

iss_model: hiseq
iss_threads: 2

reference_length_bp: 50000
seed: 1337
