name: holosimulator
channels:
    - conda-forge
    - bioconda
    - defaults

dependencies:
  - python
  - biopython
  - numpy
  - pandas
  - argparse
  - PyYAML
  - requests
  - snakemake
  - art_modern==1.1.6
  - pip
  - pip:
      - git+https://github.com/alberdilab/holosimulator.git